"use strict";
let adsData=null,gaData=null;
const detail={view:'overview',ads:{location:'all',campaign:'all',group:'all',city:'all',locationType:'all',breakdown:'campaigns',search:'',sort:'costMicros',direction:-1,page:1},ga:{breakdown:'channels',search:'',sort:'sessions',direction:-1,page:1}};
const metricKeys=['costMicros','impressions','clicks','conversions'];
const totalAds=rows=>Object.fromEntries(metricKeys.map(k=>[k,rows.reduce((s,r)=>s+r[k],0)]));
const withRates=r=>({...r,spend:r.costMicros/1e6,ctr:r.impressions?r.clicks/r.impressions:null,cpc:r.clicks?r.costMicros/1e6/r.clicks:null,cpa:r.conversions?r.costMicros/1e6/r.conversions:null,conversionRate:r.clicks?r.conversions/r.clicks:null});
const cardsHtml=cards=>cards.map(([name,value,kind,note])=>`<article class="kpi-card"><div class="kpi-head">${esc(name)}</div><div class="kpi-value">${fmt(value,kind)}</div><div class="report-note">${esc(note||'')}</div></article>`).join('');
function options(id,rows,value,label,selectedValue,all){$('#'+id).innerHTML=`<option value="all">${all}</option>`+rows.map(r=>`<option value="${esc(r[value])}">${esc(r[label])}</option>`).join('');$('#'+id).value=selectedValue;}
function switchView(view){detail.view=view;for(const v of ['overview','ads','meta','analytics'])$('#'+v+'-view').classList.toggle('hidden',v!==view);$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});for(const id of ['brand-filter','facility-filter','compare-filter'])$('#'+id).closest('label').classList.toggle('hidden',view!=='overview');$('.filter-bar').classList.toggle('detail-period',view!=='overview');$('#sidebar').classList.remove('open');const titles={overview:'Portfolio overview',ads:'Google Ads',meta:'Meta Ads',analytics:'Google Analytics'};$('.welcome-row h2').textContent=titles[view];$('.heading p').textContent='Portfolio / '+titles[view];$('.welcome-row p').textContent={overview:'Google Ads, Meta Ads, Analytics and CCStorage — monthly reporting from June 2026.',ads:'Explore spend, clicks and conversions by campaign, ad group and audience location.',meta:'Campaign, ad-set and ad performance, with evidence to guide your next decision.',analytics:'Website traffic, engagement and page activity for familyheirloomstorage.com.'}[view];if(report)render();window.scrollTo(0,0);}
function filteredCampaigns(){const s=detail.ads;return adsData.campaigns.filter(r=>r.month===state.period&&(s.location==='all'||r.location===s.location)&&(s.campaign==='all'||r.id===s.campaign));}
function adsOptions(){
 const s=detail.ads,month=adsData.campaigns.filter(r=>r.month===state.period);
 const locations=[...new Set(month.map(r=>r.location))].sort().map(name=>({name}));if(s.location!=='all'&&!locations.some(r=>r.name===s.location))s.location='all';options('ads-location',locations,'name','name',s.location,'All campaign locations');
 const campaigns=month.filter(r=>s.location==='all'||r.location===s.location);if(s.campaign!=='all'&&!campaigns.some(r=>r.id===s.campaign))s.campaign='all';options('ads-campaign',campaigns,'id','name',s.campaign,'All campaigns');
 const ids=new Set(filteredCampaigns().map(r=>r.id)),groups=adsData.groups.filter(r=>r.month===state.period&&ids.has(r.campaignId));if(s.group!=='all'&&!groups.some(r=>r.id===s.group))s.group='all';options('ads-group',groups,'id','name',s.group,'All ad groups');$('#ads-group').disabled=s.breakdown==='geography';
 const cities=[...new Set(adsData.geography.filter(r=>r.month===state.period&&ids.has(r.campaignId)).map(r=>r.city))].sort().map(name=>({name}));if(s.city!=='all'&&!cities.some(r=>r.name===s.city))s.city='all';options('ads-city',cities,'name','name',s.city,'All audience cities');
}
function adsRows(){
 const s=detail.ads,campaigns=filteredCampaigns(),map=new Map(campaigns.map(r=>[r.id,r]));
 if(s.breakdown==='campaigns')return campaigns.map(r=>withRates({...r,label:r.name,secondary:r.location}));
 if(s.breakdown==='groups')return adsData.groups.filter(r=>r.month===state.period&&map.has(r.campaignId)&&(s.group==='all'||r.id===s.group)).map(r=>withRates({...r,label:r.name,secondary:map.get(r.campaignId).name}));
 const grouped=new Map();for(const r of adsData.geography.filter(r=>r.month===state.period&&map.has(r.campaignId)&&(s.city==='all'||r.city===s.city)&&(s.locationType==='all'||r.locationType===s.locationType))){const key=r.city+'|'+r.locationType;const old=grouped.get(key)||{label:r.city,secondary:r.locationType==='LOCATION_OF_PRESENCE'?'Location of presence':r.locationType==='AREA_OF_INTEREST'?'Area of interest':r.locationType,...Object.fromEntries(metricKeys.map(k=>[k,0]))};for(const k of metricKeys)old[k]+=r[k];grouped.set(key,old);}return [...grouped.values()].map(withRates);
}
function renderAds(){
 if(!adsData)return;adsOptions();const s=detail.ads,rows=adsRows(),total=withRates(totalAds(rows));
 $('#ads-kpis').innerHTML=cardsHtml([['Spend',total.spend,'money'],['Impressions',total.impressions],['Clicks',total.clicks],['Click-through rate',total.ctr,'percent'],['Avg. cost / click',total.cpc,'money'],['Conversions',total.conversions,'number','Google Ads reported']]);
 $('#ads-scope').textContent=`${current().label} · ${s.location==='all'?'All campaign locations':s.location} · ${s.breakdown==='geography'?'Audience-location results':'Campaign / ad-group results'}. Campaign location comes from the campaign name; it is not a verified CCStorage facility link.`;
 $('#ads-geo-filters').classList.toggle('hidden',s.breakdown!=='geography');
 const full=withRates(totalAds(filteredCampaigns()));
 $('#ads-coverage').textContent=s.breakdown==='geography'?`Shown audience-location spend: ${fmt(total.spend,'money')}; selected campaigns total: ${fmt(full.spend,'money')}. City reporting omits some delivery. Presence and interest describe Google's location classification. Ad-group filtering is unavailable for this breakdown.`:`Totals follow the dropdown filters. Search filters the table only. Cost / conversion: ${fmt(total.cpa,'money')} · Conversion rate: ${fmt(total.conversionRate,'percent')}.`;
 $$('[data-ads-breakdown]').forEach(b=>b.classList.toggle('active',b.dataset.adsBreakdown===s.breakdown));
 drawTable('ads',rows,[['label',s.breakdown==='campaigns'?'Campaign':s.breakdown==='groups'?'Ad group':'Audience city','text'],['spend','Spend','money'],['impressions','Impressions'],['clicks','Clicks'],['ctr','CTR','percent'],['cpc','Avg. CPC','money'],['conversions','Conversions'],['cpa','Cost / conv.','money']],s);
}
function renderGA(){
 if(!gaData)return;const p=gaData.periods[state.period],s=p.summary;
 $('#ga-scope').textContent=`${current().label} · ${gaData.site} · ${gaData.timeZone}. Website totals are independent of storage and Ads filters.`;
 $('#ga-kpis').innerHTML=cardsHtml([['Users',s.totalUsers,'number',`${fmt(s.newUsers)} new users`],['Sessions',s.sessions],['Page views',s.screenPageViews],['Engaged sessions',s.engagedSessions],['Engagement rate',s.sessions?s.engagedSessions/s.sessions:null,'percent'],['Key events',s.keyEvents,'number','GA4 configured key events']]);
 const months=report.periods,values=months.map(p=>gaData.periods[p.id].summary.sessions),max=Math.max(1,...values);
 $('#ga-trend').setAttribute('aria-label',months.map((p,i)=>p.label+': '+fmt(values[i])+' sessions').join('; '));
 $('#ga-trend').innerHTML=`<svg viewBox="0 0 650 200" role="presentation">${months.map((p,i)=>{const h=values[i]/max*125,x=40+i*160;return `<g><title>${esc(p.label)}: ${fmt(values[i])} sessions</title><rect x="${x}" y="${160-h}" width="85" height="${h}" rx="5" fill="${p.partial?'#9ac6b3':'#24634f'}" opacity="${p.id===state.period?1:.65}"/><text x="${x+42}" y="${151-h}" text-anchor="middle" font-size="12">${fmt(values[i])}</text><text x="${x+42}" y="185" text-anchor="middle" font-size="12">${['June','July','August','Sept 1–9'][i]}</text></g>`;}).join('')}</svg>`;
 const kind=detail.ga.breakdown,quality=p.notes[kind],flags=[];if(quality.thresholding)flags.push('Google applies privacy thresholds');if(quality.sampled)flags.push('Google reports sampling');if(quality.otherRow)flags.push('Some dimensions are grouped into Other');
 $('#ga-quality').textContent=(flags.length?flags.join(' · ')+'. ':'')+'Search filters the table only. Users are not additive across rows. Key events follow GA4 configuration and are not confirmed move-ins.';
 const rows=p[kind].map(r=>({...r,label:kind==='channels'?r.sessionDefaultChannelGroup:kind==='pages'?r.pagePath:r.city,secondary:kind==='cities'?r.region+', '+r.country:'',engagementRate:r.sessions?r.engagedSessions/r.sessions:null}));
 const columns=kind==='pages'?[['label','Page path','text'],['screenPageViews','Views'],['totalUsers','Users'],['userEngagementDuration','Engagement (sec)']]:[['label',kind==='channels'?'Channel':'Visitor city','text'],['totalUsers','Users'],['sessions','Sessions'],['engagedSessions','Engaged sessions'],['engagementRate','Engagement rate','percent'],['keyEvents','Key events']];
 $$('[data-ga-breakdown]').forEach(b=>b.classList.toggle('active',b.dataset.gaBreakdown===kind));drawTable('ga',rows,columns,detail.ga);
}
function sortedRows(rows,s){return rows.filter(r=>(r.label+' '+r.secondary).toLowerCase().includes(s.search)).sort((a,b)=>{const x=a[s.sort],y=b[s.sort];if(x==null)return y==null?0:1;if(y==null)return -1;return(typeof x==='string'?x.localeCompare(y):x-y)*s.direction;});}
function drawTable(prefix,rows,columns,s){
 const filtered=sortedRows(rows,s),pages=Math.max(1,Math.ceil(filtered.length/12));s.page=Math.min(s.page,pages);const start=(s.page-1)*12;
 $('#'+prefix+'-head').innerHTML='<tr>'+columns.map(([key,label])=>`<th aria-sort="${s.sort===key?(s.direction===1?'ascending':'descending'):'none'}"><button class="detail-sort" data-key="${key}">${label} ↕</button></th>`).join('')+'</tr>';
 $('#'+prefix+'-body').innerHTML=filtered.slice(start,start+12).map(r=>'<tr>'+columns.map(([key,label,kind])=>`<td>${kind==='text'?`${prefix==='ads'&&s.breakdown==='campaigns'?`<button class="campaign-drill" data-campaign-id="${r.id}">${esc(r[key])} →</button>`:esc(r[key])}${r.secondary?`<small class="report-note">${esc(r.secondary)}</small>`:''}`:fmt(r[key],kind)}</td>`).join('')+'</tr>').join('')||`<tr><td colspan="${columns.length}">No rows match these filters.</td></tr>`;
 $('#'+prefix+'-count').textContent=filtered.length?`${start+1}–${Math.min(start+12,filtered.length)} of ${filtered.length} rows`:'No matching rows';
 $('#'+prefix+'-pages').innerHTML=`<button class="page-button" data-step="-1" ${s.page===1?'disabled':''} aria-label="Previous page">‹</button><span>${s.page} / ${pages}</span><button class="page-button" data-step="1" ${s.page===pages?'disabled':''} aria-label="Next page">›</button>`;
 $$('#'+prefix+'-head button').forEach(b=>b.onclick=()=>{s.direction=s.sort===b.dataset.key?-s.direction:-1;s.sort=b.dataset.key;prefix==='ads'?renderAds():renderGA();});
 $$('#'+prefix+'-pages button').forEach(b=>b.onclick=()=>{s.page+=Number(b.dataset.step);prefix==='ads'?renderAds():renderGA();});
 $$('.campaign-drill').forEach(b=>b.onclick=()=>{detail.ads.campaign=b.dataset.campaignId;detail.ads.breakdown='groups';detail.ads.search='';$('#ads-search').value='';detail.ads.page=1;renderAds();});
 $('#'+prefix+'-export').onclick=()=>downloadCsv(prefix,filtered,columns);
}
function downloadCsv(prefix,rows,columns){
 const cell=v=>{let str=String(v??'');if(typeof v==='string'&&/^[=+@\-\t\r]/.test(str))str="'"+str;return '"'+str.replaceAll('"','""')+'"';};
 const csv=[columns.map(c=>cell(c[1])).join(','),...rows.map(r=>columns.map(([key,,kind])=>cell(key==='label'?r.label+(r.secondary?' · '+r.secondary:''):r[key])).join(','))].join('\r\n');
 const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`FHS-${prefix}-${state.period}-${detail[prefix].breakdown}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function renderDetailViews(){
 if(!report)return; if(detail.view === 'meta' && typeof renderMeta === 'function'){renderMeta();$('#footer-note').textContent='Meta Ads · '+current().start+' through '+current().end+' · USD · Meta-reported results';}
 if(gaData){const s=gaData.periods[state.period].summary;$('#website-summary').innerHTML=`<div><strong>Website activity</strong><small>Google Analytics · ${esc(current().label)} · entire website</small></div><div><b>${fmt(s.totalUsers)}</b><small>Users</small></div><div><b>${fmt(s.sessions)}</b><small>Sessions</small></div><div><b>${fmt(s.screenPageViews)}</b><small>Page views</small></div><div><b>${fmt(s.sessions?s.engagedSessions/s.sessions:null,'percent')}</b><small>Engagement rate</small></div><button class="export-button" id="open-ga">Explore Analytics →</button>`;$('#open-ga').onclick=()=>switchView('analytics');if(!$('#ga-source'))$('#source-strip').insertAdjacentHTML('beforeend',`<div class="source-item" id="ga-source"><i class="source-logo ga">GA</i><strong>Google Analytics</strong><span>${current().start} – ${current().end}</span><b class="state ok">Loaded</b></div>`);}
 if(detail.view==='ads'){renderAds();$('#footer-note').textContent=`Google Ads · ${current().start} through ${current().end} · USD · Account timezone: America/New_York`;}if(detail.view==='analytics'){renderGA();$('#footer-note').textContent=`Google Analytics · ${current().start} through ${current().end} · ${gaData?.site||''}`;}
}
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
for(const[id,key]of[['ads-location','location'],['ads-campaign','campaign'],['ads-group','group'],['ads-city','city'],['ads-location-type','locationType']])$('#'+id).onchange=e=>{detail.ads[key]=e.target.value;detail.ads.page=1;if(key==='location'){detail.ads.campaign='all';detail.ads.group='all';}if(key==='campaign')detail.ads.group='all';if(key==='group'&&e.target.value!=='all')detail.ads.breakdown='groups';renderAds();};
$$('[data-ads-breakdown]').forEach(b=>b.onclick=()=>{Object.assign(detail.ads,{breakdown:b.dataset.adsBreakdown,page:1,sort:'costMicros',direction:-1,search:''});$('#ads-search').value='';if(detail.ads.breakdown!=='groups')detail.ads.group='all';renderAds();});
$$('[data-ga-breakdown]').forEach(b=>b.onclick=()=>{Object.assign(detail.ga,{breakdown:b.dataset.gaBreakdown,page:1,sort:b.dataset.gaBreakdown==='pages'?'screenPageViews':'sessions',direction:-1,search:''});$('#ga-search').value='';renderGA();});
for(const prefix of ['ads','ga'])$('#'+prefix+'-search').oninput=e=>{detail[prefix].search=e.target.value.toLowerCase().trim();detail[prefix].page=1;prefix==='ads'?renderAds():renderGA();};
function clearAds(){Object.assign(detail.ads,{location:'all',campaign:'all',group:'all',city:'all',locationType:'all',search:'',page:1});$('#ads-search').value='';$('#ads-location-type').value='all';if(adsData)renderAds();}
$('#ads-reset').onclick=clearAds;
$('#reset-filters').addEventListener('click',()=>{clearAds();detail.ga.search='';detail.ga.page=1;$('#ga-search').value='';renderDetailViews();});
definitions.push(['Google Analytics','Website reporting for stream G-TCSG6BY1KK. Monthly users are read directly and are not summed from page or city rows. Engagement rate is engaged sessions divided by sessions. Key events follow the current GA4 configuration.'],['Google Ads detail','Campaign locations come from campaign names. Audience locations use the separate city report, which may omit delivery and is not a facility mapping. Ad groups are the Google Ads level beneath campaigns. Ratios are recomputed from totals; zero denominators display n/a. CSV rates are numeric fractions.']);
(async()=>{const results=await Promise.allSettled([fetch('data/google-ads.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Ads data unavailable');return r.json();}),fetch('data/analytics.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Analytics data unavailable');return r.json();})]);if(results[0].status==='fulfilled'&&results[0].value.schema==='storage-signal.ads-details.v1')adsData=results[0].value;else $('#ads-scope').textContent='Google Ads detail could not be loaded. Reload to try again.';if(results[1].status==='fulfilled'&&results[1].value.schema==='storage-signal.analytics.v1')gaData=results[1].value;else{$('#ga-scope').textContent='Google Analytics could not be loaded. Reload to try again.';$('#website-summary').textContent='Google Analytics is unavailable.';}renderDetailViews();})();
