"use strict";
let adsData=null,gaData=null;
const detail={view:'overview',ads:{location:'all',campaign:'all',group:'all',city:'all',locationType:'all',breakdown:'campaigns',search:'',sort:'costMicros',direction:-1,page:1},ga:{breakdown:'channels',search:'',sort:'sessions',direction:-1,page:1}};
function availablePeriods(view=detail.view){
 const baseline=report?.periods||[];
 if(view==='ads'&&adsData?.periods)return Array.isArray(adsData.periods)?adsData.periods:Object.entries(adsData.periods).map(([id,p])=>({...p,id}));
 if(view==='analytics'&&gaData)return Object.entries(gaData.periods).map(([id,p])=>({...baseline.find(b=>b.id===id),...p,id}));
 return baseline;
}
const activePeriod=()=>availablePeriods().find(p=>p.id===state.period);
function periodCoverage(){
 const periods=availablePeriods(),months=periods.filter(p=>p.id!=='2026-ytd'),first=months[0],last=months.at(-1);
 if(!first||!last)return;
 const scope=detail.view==='overview'?'Portfolio overview':detail.view==='meta'?'Meta Ads':detail.view==='ads'?'Google Ads':'Google Analytics';
 $('#period-coverage').textContent=(detail.periodNotice||'')+`${scope} coverage: ${first.start} through ${last.end}. `+(periods.some(p=>p.id==='2026-ytd')?'Choose a month or 2026 year to date. The full calendar year is still in progress.':'Earlier months and year-to-date totals are not loaded for this view.');
}
const metricKeys=['costMicros','impressions','clicks','conversions'];
const totalAds=rows=>Object.fromEntries(metricKeys.map(k=>[k,rows.reduce((s,r)=>s+r[k],0)]));
const withRates=r=>({...r,spend:r.costMicros/1e6,ctr:r.impressions?r.clicks/r.impressions:null,cpc:r.clicks?r.costMicros/1e6/r.clicks:null,cpa:r.conversions?r.costMicros/1e6/r.conversions:null,conversionRate:r.clicks?r.conversions/r.clicks:null});
const cardsHtml=cards=>cards.map(([name,value,kind,note])=>`<article class="kpi-card"><div class="kpi-head">${esc(name)}</div><div class="kpi-value">${fmt(value,kind)}</div><div class="report-note">${esc(note||'')}</div></article>`).join('');
function options(id,rows,value,label,selectedValue,all){$('#'+id).innerHTML=`<option value="all">${all}</option>`+rows.map(r=>`<option value="${esc(r[value])}">${esc(r[label])}</option>`).join('');$('#'+id).value=selectedValue;}
function switchView(view){const previous=activePeriod();detail.view=view;detail.periodNotice='';for(const v of ['overview','ads','meta','analytics'])$('#'+v+'-view').classList.toggle('hidden',v!==view);$$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});for(const id of ['brand-filter','facility-filter','compare-filter'])$('#'+id).closest('label').classList.toggle('hidden',view!=='overview');$('.filter-bar').classList.toggle('detail-period',view!=='overview');$('#sidebar').classList.remove('open');const titles={overview:'Portfolio overview',ads:'Google Ads',meta:'Meta Ads',analytics:'Google Analytics'};$('.welcome-row h2').textContent=titles[view];$('.heading p').textContent='Portfolio / '+titles[view];$('.welcome-row p').textContent={overview:'Google Ads, Meta Ads, Analytics and CCStorage — monthly reporting from June 2026.',ads:'Explore 2026 spend, clicks and conversions by campaign, ad group and audience location.',meta:'Campaign, ad-set and ad performance, with evidence to guide your next decision.',analytics:'2026 website traffic, engagement and page activity for familyheirloomstorage.com.'}[view];if(report){renderFilters();if(previous&&previous.id!==state.period)detail.periodNotice=`${previous.label} is unavailable in this view. Showing ${activePeriod().label}. `;render();}window.scrollTo(0,0);}
function filteredCampaigns(){const s=detail.ads;return adsData.campaigns.filter(r=>r.month===state.period&&(s.location==='all'||r.location===s.location)&&(s.campaign==='all'||r.id===s.campaign));}
function adsOptions(){
 const s=detail.ads,month=adsData.campaigns.filter(r=>r.month===state.period);
 const locations=[...new Set(month.map(r=>r.location))].sort().map(name=>({name}));if(s.location!=='all'&&!locations.some(r=>r.name===s.location))s.location='all';options('ads-location',locations,'name','name',s.location,'All campaign locations');
 const campaigns=month.filter(r=>s.location==='all'||r.location===s.location);if(s.campaign!=='all'&&!campaigns.some(r=>r.id===s.campaign))s.campaign='all';options('ads-campaign',campaigns,'id','name',s.campaign,'All campaigns');
 const ids=new Set(filteredCampaigns().map(r=>r.id)),groups=adsData.groups.filter(r=>r.month===state.period&&ids.has(r.campaignId));if(s.group!=='all'&&!groups.some(r=>r.id===s.group))s.group='all';options('ads-group',groups,'id','name',s.group,'All ad groups');$('#ads-group').disabled=s.breakdown==='geography';
 const cities=[...new Set(adsData.geography.filter(r=>r.month===state.period&&ids.has(r.campaignId)).map(r=>r.city))].sort().map(name=>({name}));if(s.city!=='all'&&!cities.some(r=>r.name===s.city))s.city='all';options('ads-city',cities,'name','name',s.city,'All audience cities');
}
function adsRows(){
 const s=detail.ads,campaigns=filteredCampaigns(),map=new Map(campaigns.map(r=>[r.id,r]));
 if(s.breakdown==='campaigns')return campaigns.map(r=>withRates({...r,label:r.name,secondary:r.location}));
 if(s.breakdown==='groups')return adsData.groups.filter(r=>r.month===state.period&&map.has(r.campaignId)&&(s.group==='all'||r.id===s.group)).map(r=>withRates({...r,label:r.name,secondary:map.get(r.campaignId).name}));
 const grouped=new Map();for(const r of adsData.geography.filter(r=>r.month===state.period&&map.has(r.campaignId)&&(s.city==='all'||r.city===s.city)&&(s.locationType==='all'||r.locationType===s.locationType))){const key=r.city+'|'+r.locationType;const old=grouped.get(key)||{label:r.city,secondary:r.locationType==='LOCATION_OF_PRESENCE'?'Location of presence':r.locationType==='AREA_OF_INTEREST'?'Area of interest':r.locationType,...Object.fromEntries(metricKeys.map(k=>[k,0]))};for(const k of metricKeys)old[k]+=r[k];grouped.set(key,old);}return [...grouped.values()].map(withRates);
}
function renderAds(){
 if(!adsData)return;adsOptions();const s=detail.ads,rows=adsRows(),account=adsData.accountTotals?.find(r=>r.month===state.period),unfiltered=s.location==='all'&&s.campaign==='all'&&s.group==='all'&&s.breakdown!=='geography',total=withRates(unfiltered&&account?account:totalAds(rows)),p=activePeriod();
 $('#ads-kpis').innerHTML=cardsHtml([['Spend',total.spend,'money'],['Impressions',total.impressions],['Clicks',total.clicks],['Click-through rate',total.ctr,'percent'],['Avg. cost / click',total.cpc,'money'],['Conversions',total.conversions,'number','Google Ads reported']]);
 $('#ads-scope').textContent=`${p.label} · ${p.start} through ${p.end} · ${s.location==='all'?'All campaign locations':s.location} · ${s.breakdown==='geography'?'Audience-location results':'Campaign / ad-group results'}. Campaign location comes from the campaign name; it is not a verified CCStorage facility link.`+(adsData.coverage?.[state.period]?.status==='no_delivery'?' Google Ads returned no recorded delivery for this period.':'');
 $('#ads-geo-filters').classList.toggle('hidden',s.breakdown!=='geography');
 const full=withRates(s.location==='all'&&s.campaign==='all'&&account?account:totalAds(filteredCampaigns()));
 $('#ads-coverage').textContent=s.breakdown==='geography'?`Shown audience-location spend: ${fmt(total.spend,'money')}; selected campaigns total: ${fmt(full.spend,'money')}. City reporting omits some delivery. Presence and interest describe Google's location classification. Ad-group filtering is unavailable for this breakdown.`:`Totals follow the dropdown filters. Search filters the table only. Cost / conversion: ${fmt(total.cpa,'money')} · Conversion rate: ${fmt(total.conversionRate,'percent')}.`;
 $$('[data-ads-breakdown]').forEach(b=>b.classList.toggle('active',b.dataset.adsBreakdown===s.breakdown));
 drawTable('ads',rows,[['label',s.breakdown==='campaigns'?'Campaign':s.breakdown==='groups'?'Ad group':'Audience city','text'],['spend','Spend','money'],['impressions','Impressions'],['clicks','Clicks'],['ctr','CTR','percent'],['cpc','Avg. CPC','money'],['conversions','Conversions'],['cpa','Cost / conv.','money']],s);
}
function renderGA(){
 if(!gaData)return;const p=gaData.periods[state.period],s=p?.summary||{},period=activePeriod(),missing=!p?.summary;
 $('#ga-scope').textContent=`${period.label} · ${period.start} through ${period.end} · ${gaData.site} · ${gaData.timeZone}. Website totals are independent of storage and Ads filters.`;
 const coverage=p?.coverage?.note||gaData.coverage?.note||'';
 const coverageNode=$('#ga-data-coverage');coverageNode.hidden=!missing&&!coverage;
 coverageNode.innerHTML=`<strong>${missing?'No recorded GA4 data for this period':state.period==='2026-ytd'?'2026 year-to-date coverage':'GA4 coverage'}</strong><p>${esc(coverage||(missing?'GA4 returned no recorded activity. This is unavailable history, not a measured zero.':'Recorded activity for the selected period.'))}</p>`;
 if(gaData.coverage?.earliestObservedDate&&!coverage.includes(gaData.coverage.earliestObservedDate)&&(missing||state.period==='2026-ytd'||period.start<gaData.coverage.earliestObservedDate))coverageNode.insertAdjacentHTML('beforeend',`<p>First recorded activity in the queried 2026 history: ${esc(gaData.coverage.earliestObservedDate)}.</p>`);
 if(state.period==='2026-ytd'&&!missing)coverageNode.insertAdjacentHTML('beforeend','<p>Users come from the single year-to-date report and are deduplicated across the selected dates. Monthly user counts are not added together.</p>');
 if(period.partial&&gaData.coverage?.freshnessNote)coverageNode.insertAdjacentHTML('beforeend',`<p>${esc(gaData.coverage.freshnessNote)}</p>`);
 $('#ga-kpis').innerHTML=cardsHtml([['Users',s.totalUsers,'number',missing?'No recorded data':`${fmt(s.newUsers)} new users`],['Sessions',s.sessions],['Page views',s.screenPageViews],['Engaged sessions',s.engagedSessions],['Engagement rate',s.sessions?s.engagedSessions/s.sessions:null,'percent'],['Key events',s.keyEvents,'number','GA4 configured key events']]);
 const months=availablePeriods('analytics').filter(p=>p.id!=='2026-ytd'),values=months.map(p=>gaData.periods[p.id]?.summary?.sessions??null),max=Math.max(1,...values.filter(v=>v!==null)),width=Math.max(650,months.length*86),step=(width-30)/Math.max(1,months.length),bar=Math.min(70,step*.65);
 $('#ga-trend').setAttribute('aria-label',months.map((p,i)=>p.label+': '+(values[i]===null?'No recorded data':fmt(values[i])+' sessions')).join('; '));
 $('#ga-trend').innerHTML=`<svg viewBox="0 0 ${width} 200" role="presentation" style="min-width:${width}px">${months.map((p,i)=>{const v=values[i],h=v===null?0:v/max*125,x=15+i*step+(step-bar)/2,label=new Date(p.start+'T00:00:00Z').toLocaleDateString('en-US',{month:'short',timeZone:'UTC'})+(p.partial?'*':'');return `<g><title>${esc(p.label)}: ${v===null?'No recorded data':fmt(v)+' sessions'}</title>${v===null?`<line x1="${x}" x2="${x+bar}" y1="160" y2="160" stroke="#7e8b85" stroke-dasharray="4 3"/>`:`<rect x="${x}" y="${160-h}" width="${bar}" height="${h}" rx="5" fill="${p.partial?'#9ac6b3':'#24634f'}" opacity="${p.id===state.period||state.period==='2026-ytd'?1:.65}"/>`}<text x="${x+bar/2}" y="${151-h}" text-anchor="middle" font-size="12">${v===null?'No data':fmt(v)}</text><text x="${x+bar/2}" y="185" text-anchor="middle" font-size="12">${label}</text></g>`;}).join('')}</svg>`;
 const partial=months.find(p=>p.partial);$('#ga-trend-note').textContent=`Monthly sessions · ${months[0]?.start||''} through ${months.at(-1)?.end||''}`+(partial?' · * Partial month':'')+' · Gaps mean no recorded data';
 const kind=detail.ga.breakdown,quality=p?.notes?.[kind]||{},flags=[];if(quality.thresholding)flags.push('Google applies privacy thresholds');if(quality.sampled)flags.push('Google reports sampling');if(quality.otherRow)flags.push('Some dimensions are grouped into Other');
 $('#ga-quality').textContent=(missing?'No recorded GA4 data was returned for the selected dates. ':flags.length?flags.join(' · ')+'. ':'')+'Search filters the table only. Users are not additive across rows. Key events follow GA4 configuration and are not confirmed move-ins.'+(kind==='pages'&&quality.privatePathRowsOmitted?` Private paths are grouped into one omitted-path row (${fmt(quality.privatePathViews)} views); its user count is unavailable.`:'');
 const rows=(p?.[kind]||[]).map(r=>({...r,label:kind==='channels'?r.sessionDefaultChannelGroup:kind==='pages'?r.pagePath:r.city,secondary:kind==='cities'?r.region+', '+r.country:'',engagementRate:r.sessions?r.engagedSessions/r.sessions:null}));
 const columns=kind==='pages'?[['label','Page path','text'],['screenPageViews','Views'],['totalUsers','Users'],['userEngagementDuration','Engagement (sec)']]:[['label',kind==='channels'?'Channel':'Visitor city','text'],['totalUsers','Users'],['sessions','Sessions'],['engagedSessions','Engaged sessions'],['engagementRate','Engagement rate','percent'],['keyEvents','Key events']];
 $$('[data-ga-breakdown]').forEach(b=>b.classList.toggle('active',b.dataset.gaBreakdown===kind));drawTable('ga',rows,columns,detail.ga);if(missing)$('#ga-body').innerHTML=`<tr><td colspan="${columns.length}">No recorded GA4 data for ${esc(period.label)}. Select a month with recorded activity to explore its breakdown.</td></tr>`;
}
function sortedRows(rows,s){return rows.filter(r=>(r.label+' '+r.secondary).toLowerCase().includes(s.search)).sort((a,b)=>{const x=a[s.sort],y=b[s.sort];if(x==null)return y==null?0:1;if(y==null)return -1;return(typeof x==='string'?x.localeCompare(y):x-y)*s.direction;});}
function drawTable(prefix,rows,columns,s){
 const filtered=sortedRows(rows,s),pages=Math.max(1,Math.ceil(filtered.length/12));s.page=Math.min(s.page,pages);const start=(s.page-1)*12;
 $('#'+prefix+'-head').innerHTML='<tr>'+columns.map(([key,label])=>`<th aria-sort="${s.sort===key?(s.direction===1?'ascending':'descending'):'none'}"><button class="detail-sort" data-key="${key}">${label} ↕</button></th>`).join('')+'</tr>';
 $('#'+prefix+'-body').innerHTML=filtered.slice(start,start+12).map(r=>'<tr>'+columns.map(([key,label,kind])=>`<td>${kind==='text'?`${prefix==='ads'&&s.breakdown==='campaigns'?`<button class="campaign-drill" data-campaign-id="${r.id}">${esc(r[key])} →</button>`:esc(r[key])}${r.secondary?`<small class="report-note">${esc(r.secondary)}</small>`:''}`:fmt(r[key],kind)}</td>`).join('')+'</tr>').join('')||`<tr><td colspan="${columns.length}">No rows match these filters.</td></tr>`;
 $('#'+prefix+'-count').textContent=filtered.length?`${start+1}–${Math.min(start+12,filtered.length)} of ${filtered.length} rows`:'No matching rows';
 $('#'+prefix+'-pages').innerHTML=`<button class="page-button" data-step="-1" ${s.page===1?'disabled':''} aria-label="Previous page">‹</button><span>${s.page} / ${pages}</span><button class="page-button" data-step="1" ${s.page===pages?'disabled':''} aria-label="Next page">›</button>`;
 $$('#'+prefix+'-head button').forEach(b=>b.onclick=()=>{s.direction=s.sort===b.dataset.key?-s.direction:-1;s.sort=b.dataset.key;prefix==='ads'?renderAds():renderGA();});
 $$('#'+prefix+'-pages button').forEach(b=>b.onclick=()=>{s.page+=Number(b.dataset.step);prefix==='ads'?renderAds():renderGA();});
 $$('.campaign-drill').forEach(b=>b.onclick=()=>{detail.ads.campaign=b.dataset.campaignId;detail.ads.breakdown='groups';detail.ads.search='';$('#ads-search').value='';detail.ads.page=1;renderAds();});
 $('#'+prefix+'-export').disabled=!filtered.length;$('#'+prefix+'-export').onclick=()=>downloadCsv(prefix,filtered,columns);
}
function downloadCsv(prefix,rows,columns){
 const cell=v=>{let str=String(v??'');if(typeof v==='string'&&/^[=+@\-\t\r]/.test(str))str="'"+str;return '"'+str.replaceAll('"','""')+'"';};
 const csv=[columns.map(c=>cell(c[1])).join(','),...rows.map(r=>columns.map(([key,,kind])=>cell(key==='label'?r.label+(r.secondary?' · '+r.secondary:''):r[key])).join(','))].join('\r\n');
 const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`FHS-${prefix}-${state.period}-${detail[prefix].breakdown}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function renderDetailViews(){
 if(!report)return;renderFilters();periodCoverage();const p=activePeriod();if(!p)return;
 if(detail.view!=='overview'){
  const source=detail.view==='ads'?adsData:detail.view==='analytics'?gaData:report,name=detail.view==='ads'?'Google Ads':detail.view==='analytics'?'Google Analytics':'Meta Ads',cls=detail.view==='ads'?'google':detail.view==='analytics'?'ga':'meta',missing=detail.view==='analytics'&&gaData&&!gaData.periods[state.period]?.summary,status=!source?'Unavailable':missing?'No recorded data':'Loaded';
  $('#mode-ribbon').textContent=`${p.id==='2026-ytd'?'Year-to-date':'Monthly'} reporting · ${p.label}`+(detail.view==='analytics'?'':' · USD');
  $('#snapshot-label').textContent=`Updated ${source?.refreshed||report.refreshed}`;$('#facility-count').textContent=`${report.periods[0].facilities.length} facilities`;
  $('#freshness').innerHTML=`<span class="freshness-dot"></span><div><strong>${esc(p.label)}</strong><small>${esc(name)} refreshed ${esc(source?.refreshed||'unavailable')}</small></div>`;
  $('#source-strip').innerHTML=`<div class="source-item"><i class="source-logo ${cls}">${detail.view==='analytics'?'GA':name[0]}</i><strong>${name}</strong><span>${esc(p.start)} – ${esc(p.end)}</span><b class="state ${source&&!missing?'ok':'warn'}">${status}</b></div>`;
 }
 if(detail.view==='meta'&&typeof renderMeta==='function'){renderMeta();$('#footer-note').textContent=`Meta Ads · ${p.start} through ${p.end} · USD · Meta-reported results`;}
 if(detail.view==='overview'&&gaData){const summary=gaData.periods[state.period]?.summary,s=summary||{};$('#website-summary').innerHTML=`<div><strong>Website activity</strong><small>Google Analytics · ${esc(p.label)} · entire website${summary?'':' · No recorded data'}</small></div><div><b>${fmt(s.totalUsers)}</b><small>Users</small></div><div><b>${fmt(s.sessions)}</b><small>Sessions</small></div><div><b>${fmt(s.screenPageViews)}</b><small>Page views</small></div><div><b>${fmt(s.sessions?s.engagedSessions/s.sessions:null,'percent')}</b><small>Engagement rate</small></div><button class="export-button" id="open-ga">Explore Analytics →</button>`;$('#open-ga').onclick=()=>switchView('analytics');$('#ga-source')?.remove();$('#source-strip').insertAdjacentHTML('beforeend',`<div class="source-item" id="ga-source"><i class="source-logo ga">GA</i><strong>Google Analytics</strong><span>${p.start} – ${p.end}</span><b class="state ${summary?'ok':'warn'}">${summary?'Loaded':'No recorded data'}</b></div>`);}
 if(detail.view==='ads'){renderAds();$('#footer-note').textContent=`Google Ads · ${p.start} through ${p.end} · USD · Account timezone: America/New_York`;}if(detail.view==='analytics'){renderGA();$('#footer-note').textContent=`Google Analytics · ${p.start} through ${p.end} · ${gaData?.site||''}`;}
}
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
for(const[id,key]of[['ads-location','location'],['ads-campaign','campaign'],['ads-group','group'],['ads-city','city'],['ads-location-type','locationType']])$('#'+id).onchange=e=>{detail.ads[key]=e.target.value;detail.ads.page=1;if(key==='location'){detail.ads.campaign='all';detail.ads.group='all';}if(key==='campaign')detail.ads.group='all';if(key==='group'&&e.target.value!=='all')detail.ads.breakdown='groups';renderAds();};
$$('[data-ads-breakdown]').forEach(b=>b.onclick=()=>{Object.assign(detail.ads,{breakdown:b.dataset.adsBreakdown,page:1,sort:'costMicros',direction:-1,search:''});$('#ads-search').value='';if(detail.ads.breakdown!=='groups')detail.ads.group='all';renderAds();});
$$('[data-ga-breakdown]').forEach(b=>b.onclick=()=>{Object.assign(detail.ga,{breakdown:b.dataset.gaBreakdown,page:1,sort:b.dataset.gaBreakdown==='pages'?'screenPageViews':'sessions',direction:-1,search:''});$('#ga-search').value='';renderGA();});
for(const prefix of ['ads','ga'])$('#'+prefix+'-search').oninput=e=>{detail[prefix].search=e.target.value.toLowerCase().trim();detail[prefix].page=1;prefix==='ads'?renderAds():renderGA();};
function clearAds(){Object.assign(detail.ads,{location:'all',campaign:'all',group:'all',city:'all',locationType:'all',search:'',page:1});$('#ads-search').value='';$('#ads-location-type').value='all';if(adsData&&detail.view==='ads')renderAds();}
$('#ads-reset').onclick=clearAds;
$('#reset-filters').addEventListener('click',()=>{detail.periodNotice='';clearAds();detail.ga.search='';detail.ga.page=1;$('#ga-search').value='';renderDetailViews();});
definitions.push(['Google Analytics','Website reporting for stream G-TCSG6BY1KK. Monthly and year-to-date users are each read directly for the selected dates; users are not summed across months, pages or cities. Missing recorded history displays n/a, not zero. Engagement rate is engaged sessions divided by sessions. Key events follow the current GA4 configuration.'],['Google Ads detail','Campaign locations come from campaign names. Audience locations use the separate city report, which may omit delivery and is not a facility mapping. Ad groups are the Google Ads level beneath campaigns. Ratios are recomputed from totals; zero denominators display n/a. CSV rates are numeric fractions.'],['2026 coverage','Google Ads and GA4 offer monthly reporting and a year-to-date view through September 9. The year is still in progress. Overview, Meta and CCStorage retain their available June–September periods. The selected period falls back to August when it is unavailable in the next view.']);
(async()=>{const results=await Promise.allSettled([fetch('data/google-ads.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Ads data unavailable');return r.json();}),fetch('data/analytics.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Analytics data unavailable');return r.json();})]);if(results[0].status==='fulfilled'&&results[0].value.schema==='storage-signal.ads-details.v1')adsData=results[0].value;else $('#ads-scope').textContent='Google Ads detail could not be loaded. Reload to try again.';if(results[1].status==='fulfilled'&&results[1].value.schema==='storage-signal.analytics.v1')gaData=results[1].value;else{$('#ga-scope').textContent='Google Analytics could not be loaded. Reload to try again.';$('#website-summary').textContent='Google Analytics is unavailable.';}renderDetailViews();})();
