"use strict";

(function (root, factory) {
 const api = factory();
 if (typeof module !== "undefined" && module.exports) module.exports = api;
 if (root) root.journeyDashboard = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
 const PAGE_SIZE = 50;
 const LEADS_SCHEMA = "storage-signal.leads.v1";
 const VISITORS_SCHEMA = "storage-signal.visitors.v1";
 const KEY_EVENTS = ["generate_lead","contact","form_submit","begin_checkout","outbound_click","ccstorage_rental_completed"];
 let leadsPromise,visitorsPromise,leadsIndex,visitorsIndex;
 let leadsUnavailable=false,visitorsUnavailable=false;
 let leadView,visitorView;
 const weekPromises=new Map();
 const html=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]));
 const number=value=>new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(Number(value||0));
 const currency=value=>value==null?"n/a":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(value));
 const percent=value=>value==null?"n/a":new Intl.NumberFormat("en-US",{style:"percent",maximumFractionDigits:1}).format(Number(value));
 const day=value=>String(value||"").slice(0,10)||"Not recorded";
 const toDate=value=>new Date(`${value}T00:00:00Z`);
 const iso=value=>value.toISOString().slice(0,10);
 const addDays=(value,amount)=>{const result=toDate(value);result.setUTCDate(result.getUTCDate()+amount);return iso(result);};
 const clamp=(value,minimum,maximum)=>value<minimum?minimum:value>maximum?maximum:value;

 function presetRange(minimum,maximum,preset){
  let from,to=maximum;
  if(preset==="this-month")from=`${maximum.slice(0,7)}-01`;
  else if(preset==="last-month"){const first=toDate(`${maximum.slice(0,7)}-01`);first.setUTCMonth(first.getUTCMonth()-1);from=iso(first);first.setUTCMonth(first.getUTCMonth()+1);first.setUTCDate(0);to=iso(first);}
  else if(preset==="last-7")from=addDays(maximum,-6);
  else if(preset==="last-30")from=addDays(maximum,-29);
  else return null;
  from=clamp(from,minimum,maximum);to=clamp(to,minimum,maximum);if(from>to)from=to;
  return {from,to};
 }

 function leadCoverage(data){return data.leads.map(row=>row.created_date).sort()[0]||data.cutoff;}
 function visitorCoverage(data){return data.start||data.visitors.map(row=>day(row.first_seen)).sort()[0]||data.through;}
 function initialLeadView(data){const range=presetRange(leadCoverage(data),data.cutoff,"last-30");return {preset:"last-30",...range,campaign:"all",match:"all",search:"",sort:"created_date",direction:-1,page:1};}
 function initialVisitorView(data){const range=presetRange(visitorCoverage(data),data.through,"last-30");return {preset:"last-30",...range,channel:"all",search:"",keyOnly:false,sort:"first_seen",direction:-1,page:1};}

 function matchedTiming(lead){
  const matches=lead.match?.matches||[];
  if(matches.some(item=>item.timing==="already a tenant"))return "Already a tenant";
  const days=matches.map(item=>item.days_to_move_in).filter(value=>value!=null);
  return days.length?`${Math.min(...days)} days to move-in`:"No move-in yet";
 }
 function isNewRenter(lead){const matches=lead.match?.matches||[];return lead.match?.status==="confirmed"&&!matches.some(item=>item.timing==="already a tenant")&&matches.some(item=>item.days_to_move_in!=null);}
 function isAlreadyTenant(lead){return lead.match?.status==="confirmed"&&(lead.match?.matches||[]).some(item=>item.timing==="already a tenant");}
 function leadRows(data,view){const query=view.search.trim().toLowerCase();return data.leads.filter(row=>row.created_date>=view.from&&row.created_date<=view.to&&(view.campaign==="all"||row.campaign?.key===view.campaign)&&(view.match==="all"||row.match?.status===view.match)&&(!query||row.display_name.toLowerCase().includes(query)));}
 function sorted(rows,view){return [...rows].sort((a,b)=>{let left=a[view.sort],right=b[view.sort];if(view.sort==="campaign"){left=a.campaign?.name;right=b.campaign?.name;}if(view.sort==="match"){left=a.match?.status;right=b.match?.status;}if(view.sort==="timing"){left=matchedTiming(a);right=matchedTiming(b);}return String(left??"").localeCompare(String(right??""),undefined,{numeric:true})*view.direction;});}
 function leadBadge(lead){return `<span class="journey-match-badge ${html(lead.match?.status||"none")}">${html(lead.match?.label||"No renter match")}${lead.match?.multiple?" · Multiple renters":""}</span>`;}

 function leadCards(rows){
  const newRenters=rows.filter(isNewRenter),already=rows.filter(isAlreadyTenant),possible=rows.filter(row=>row.match?.status==="possible");
  const days=newRenters.flatMap(row=>(row.match?.matches||[]).map(item=>item.days_to_move_in).filter(value=>value!=null)).sort((a,b)=>a-b);
  const median=days.length?(days.length%2?days[(days.length-1)/2]:(days[days.length/2-1]+days[days.length/2])/2):null;
  return [["Leads",rows.length,"In selected range"],["Confirmed renters (new)",newRenters.length,"Moved in after the lead"],["Already tenants",already.length,"Active on the lead date"],["Possible matches",possible.length,"Name and timing · unconfirmed"],["Confirmed lead-to-renter rate",rows.length?newRenters.length/rows.length:null,"Confirmed new renters / leads","percent"],["Median days to move-in",median,median==null?"No confirmed new renters":"Confirmed new renters","days"]];
 }
 function sortButton(key,label,view){const active=view.sort===key;return `<button type="button" data-journey-sort="${key}" aria-label="Sort by ${html(label)}">${html(label)} ${active?(view.direction===1?"↑":"↓"):"↕"}</button>`;}
 function pagination(total,page,prefix){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),safe=Math.min(page,pages);return `<footer class="table-footer"><span>${total?`${(safe-1)*PAGE_SIZE+1}–${Math.min(safe*PAGE_SIZE,total)} of ${total}`:"No matching records."}</span><div class="pagination"><button class="page-button" type="button" data-${prefix}-page="${safe-1}" ${safe===1?"disabled":""} aria-label="Previous page">‹</button><span>${safe} / ${pages}</span><button class="page-button" type="button" data-${prefix}-page="${safe+1}" ${safe===pages?"disabled":""} aria-label="Next page">›</button></div></footer>`;}

 function renderLeadTable(rows,view){
  const ordered=sorted(rows,view),pages=Math.max(1,Math.ceil(ordered.length/PAGE_SIZE)),page=Math.min(view.page,pages),shown=ordered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const body=shown.map(row=>`<tr><td>${html(row.created_date)}</td><td class="tenant-name-cell"><button type="button" class="tenant-name" data-lead-id="${html(row.id)}">${html(row.display_name)}</button></td><td>${html(row.campaign?.name||"Unknown")}<small>${html(row.campaign?.source==="formAds"?"Campaign inferred from form's ads":"Campaign returned on lead")}</small></td><td>${html(row.form)}</td><td>${html(row.platform)}${row.organic?" · Organic":""}</td><td>${leadBadge(row)}</td><td>${html(matchedTiming(row))}</td></tr>`).join("")||'<tr><td colspan="7" class="tenant-empty">No matching records.</td></tr>';
  return `<div class="tenant-table-scroll" tabindex="0" role="region" aria-label="Meta leads"><table class="tenant-table journey-leads-table"><thead><tr><th>${sortButton("created_date","Date",view)}</th><th>${sortButton("display_name","Lead",view)}</th><th>${sortButton("campaign","Campaign",view)}</th><th>Form</th><th>Platform</th><th>${sortButton("match","Match",view)}</th><th>${sortButton("timing","Timing",view)}</th></tr></thead><tbody>${body}</tbody></table></div>${pagination(ordered.length,page,"lead")}`;
 }
 function campaignRows(data,rows){
  const definitions=new Map(data.byCampaign.map(item=>[item.key,item]));
  const grouped=new Map();
  for(const lead of rows){const key=lead.campaign?.key;const item=grouped.get(key)||{key,name:lead.campaign?.name||"Unknown",leads:0,newRenters:0,possible:0,months:new Set()};item.leads++;item.newRenters+=Number(isNewRenter(lead));item.possible+=Number(lead.match?.status==="possible");item.months.add(lead.created_date.slice(0,7));grouped.set(key,item);}
  return [...grouped.values()].sort((a,b)=>b.leads-a.leads||a.name.localeCompare(b.name)).map(item=>{const definition=definitions.get(item.key),monthly=definition?.spend_by_month||{},values=[...item.months].map(month=>monthly[month]).filter(value=>value!=null),spend=values.length?values.reduce((sum,value)=>sum+Number(value),0):definition?.meta_spend;return {...item,spend,cost:item.newRenters&&spend!=null?spend/item.newRenters:null};});
 }
 function renderCampaignTable(data,rows){const body=campaignRows(data,rows).map(row=>`<tr><td>${html(row.name)}</td><td class="tenant-number">${number(row.leads)}</td><td class="tenant-number">${number(row.newRenters)}</td><td class="tenant-number">${number(row.possible)}</td><td class="tenant-number">${currency(row.spend)}</td><td class="tenant-number"><strong>${currency(row.cost)}</strong><small>At least — leads may use other contact details</small></td></tr>`).join("")||'<tr><td colspan="6" class="tenant-empty">No matching records.</td></tr>';return `<div class="tenant-table-scroll" tabindex="0"><table class="tenant-table journey-campaign-table"><thead><tr><th>Campaign</th><th class="tenant-number">Leads</th><th class="tenant-number">Confirmed new renters</th><th class="tenant-number">Possible</th><th class="tenant-number">Meta spend</th><th class="tenant-number">Spend per confirmed renter</th></tr></thead><tbody>${body}</tbody></table></div>`;}

 function renderLeadsView(data,view=initialLeadView(data)){
  const rows=leadRows(data,view),minimum=leadCoverage(data),campaigns=[...new Map(data.leads.map(row=>[row.campaign?.key,row.campaign?.name||"Unknown"]))].sort((a,b)=>a[1].localeCompare(b[1]));
  return `<h2 class="sr-only" data-leads-heading tabindex="-1">Lead reporting</h2><section class="tenant-filter-bar journey-filter-bar" aria-label="Lead filters"><label><span>Date range</span><select id="lead-preset"><option value="this-month"${view.preset==="this-month"?" selected":""}>This month</option><option value="last-month"${view.preset==="last-month"?" selected":""}>Last month</option><option value="last-7"${view.preset==="last-7"?" selected":""}>Last 7 days</option><option value="last-30"${view.preset==="last-30"?" selected":""}>Last 30 days</option><option value="custom"${view.preset==="custom"?" selected":""}>Custom</option></select></label><label><span>From</span><input id="lead-from" type="date" min="${minimum}" max="${data.cutoff}" value="${view.from}" ${view.preset==="custom"?"":"disabled"}></label><label><span>To</span><input id="lead-to" type="date" min="${minimum}" max="${data.cutoff}" value="${view.to}" ${view.preset==="custom"?"":"disabled"}></label><label><span>Campaign</span><select id="lead-campaign"><option value="all">All campaigns</option>${campaigns.map(([key,name])=>`<option value="${html(key)}"${view.campaign===key?" selected":""}>${html(name)}</option>`).join("")}</select></label><label><span>Match status</span><select id="lead-match"><option value="all">All statuses</option>${[["confirmed","Confirmed"],["possible","Possible"],["none","No match"]].map(([value,label])=>`<option value="${value}"${view.match===value?" selected":""}>${label}</option>`).join("")}</select></label><label class="tenant-search"><span>Search</span><input id="lead-search" type="search" value="${html(view.search)}" placeholder="Lead name"></label><span class="tenant-cutoff">Data through ${html(data.cutoff)}</span></section><section class="tenant-scorecards journey-scorecards" aria-label="Lead summary">${leadCards(rows).map(([label,value,note,kind])=>`<article class="tenant-scorecard journey-scorecard"><span>${html(label)}</span><strong>${kind==="percent"?percent(value):kind==="days"&&value!=null?`${number(value)} days`:value==null?"n/a":number(value)}</strong><small>${html(note)}</small></article>`).join("")}</section><section class="panel tenant-activity-panel journey-campaign-panel"><header class="panel-header"><div><h3>By campaign</h3><p>Identity-matched renters only; cost is a lower bound.</p></div></header>${renderCampaignTable(data,rows)}</section><section class="panel tenant-activity-panel journey-table-panel"><header class="panel-header"><div><h3>Leads</h3><p>${html(data.summary.reconciliation_note)}${data.summary.later_leads_excluded?` · ${number(data.summary.later_leads_excluded)} later leads excluded.`:""}</p></div></header>${renderLeadTable(rows,view)}</section>`;
 }

 function renderAnswers(answers){const entries=Object.entries(answers||{});return entries.length?`<dl class="journey-answer-list">${entries.map(([question,answer])=>`<div><dt>${html(question.replaceAll("_"," "))}</dt><dd>${html(answer)}</dd></div>`).join("")}</dl>`:'<p class="tenant-empty">No non-contact answers recorded.</p>';}
 function renderLeadDialog(lead){
  const matches=lead.match?.matches||[];
  const renterSteps=matches.map(match=>`<article class="journey-timeline-item"><span class="journey-timeline-dot"></span><div><header><h3>${html(match.timing==="already a tenant"?"Existing renter":"Lease and move-in")}</h3>${leadBadge(lead)}</header><p>${match.lease_signed?`Lease signed ${html(day(match.lease_signed))}. `:""}${match.move_in_date?`Move-in ${html(match.move_in_date)}${match.days_to_move_in!=null?` · ${number(match.days_to_move_in)} days after lead`:""}.`:"No move-in recorded after the lead."}</p><p>${number(match.payments?.count)} recorded payments · ${currency(match.payments?.net)} net.</p><button type="button" class="tenant-facility-link journey-profile-link" data-journey-customer="${html(match.customer_id)}" data-journey-company="${html(match.company_id)}">View renter profile</button></div></article>`).join("");
  return `<section class="journey-dialog-summary"><div><span>${html(lead.created_date)}</span><h3>${html(lead.display_name)}</h3></div>${leadBadge(lead)}</section><div class="journey-timeline"><article class="journey-timeline-item"><span class="journey-timeline-dot"></span><div><header><h3>Meta lead</h3><span>${html(lead.platform)}${lead.organic?" · Organic":""}</span></header><p><strong>${html(lead.campaign?.name||"Unknown campaign")}</strong> · ${html(lead.adset)} · ${html(lead.ad)}<br>${html(lead.form)} · Campaign source: ${html(lead.campaign?.source||"unknown")}</p>${renderAnswers(lead.answers)}</div></article>${renterSteps||'<article class="journey-timeline-item"><span class="journey-timeline-dot"></span><div><h3>No renter match</h3><p>No confirmed contact match or qualifying possible name-and-timing match was found.</p></div></article>'}</div>`;
 }

 function channelLabel(visitor){return `${visitor.first_touch?.source||"(direct)"} / ${visitor.first_touch?.medium||"(none)"}`;}
 function visitorRows(data,view){const query=view.search.trim().toLowerCase();return data.visitors.filter(row=>day(row.first_seen)>=view.from&&day(row.first_seen)<=view.to&&(view.channel==="all"||channelLabel(row)===view.channel)&&(!query||row.landing_path.toLowerCase().includes(query))&&(!view.keyOnly||Object.values(row.key_events||{}).some(Number)));}
 function visitorEventTotal(visitor){return Object.values(visitor.key_events||{}).reduce((sum,value)=>sum+Number(value||0),0);}
 function renderChannelMix(rows){const counts=new Map();for(const row of rows)counts.set(channelLabel(row),(counts.get(channelLabel(row))||0)+1);const ranked=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])),maximum=Math.max(1,...ranked.map(item=>item[1]));return ranked.length?`<ul class="journey-channel-list">${ranked.map(([label,count])=>`<li><span>${html(label)}</span><svg viewBox="0 0 100 10" preserveAspectRatio="none" role="img" aria-label="${html(label)}: ${count} visitors"><rect class="journey-channel-track" width="100" height="10" rx="3"/><rect class="journey-channel-bar" width="${count/maximum*100}" height="10" rx="3"/></svg><strong>${number(count)}</strong></li>`).join("")}</ul>`:'<p class="tenant-empty">No matching visitors.</p>';}
 function renderVisitorTable(rows,view){const ordered=sorted(rows,view),pages=Math.max(1,Math.ceil(ordered.length/PAGE_SIZE)),page=Math.min(view.page,pages),shown=ordered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);const body=shown.map(row=>`<tr><td><button type="button" class="tenant-name journey-visitor-id" data-visitor-id="${html(row.vid)}">${html(row.vid)}</button></td><td>${html(day(row.first_seen))}</td><td>${html(channelLabel(row))}</td><td class="journey-path-cell">${html(row.landing_path)}</td><td class="tenant-number">${number(row.sessions)}</td><td class="tenant-number">${number(visitorEventTotal(row))}</td></tr>`).join("")||'<tr><td colspan="6" class="tenant-empty">No matching records.</td></tr>';return `<div class="tenant-table-scroll" tabindex="0"><table class="tenant-table journey-visitors-table"><thead><tr><th>${sortButton("vid","Visitor",view)}</th><th>${sortButton("first_seen","First seen",view)}</th><th>Source / medium</th><th>Landing page</th><th class="tenant-number">${sortButton("sessions","Sessions",view)}</th><th class="tenant-number">Key events</th></tr></thead><tbody>${body}</tbody></table></div>${pagination(ordered.length,page,"visitor")}`;}
 function visitorCards(rows){return [["Visitors",rows.length],["Sessions",rows.reduce((sum,row)=>sum+Number(row.sessions||0),0)],["Returning visitors",rows.filter(row=>row.sessions>1).length],["Lead form submits",rows.reduce((sum,row)=>sum+Number(row.key_events?.form_submit||0),0)],["Phone clicks",rows.reduce((sum,row)=>sum+Number(row.key_events?.contact||0),0)],["Rental portal visits",rows.filter(row=>row.portal_hosts?.length).length]];}

 function renderVisitorsView(data,view=initialVisitorView(data)){
  const rows=visitorRows(data,view),minimum=visitorCoverage(data),channels=[...new Set(data.visitors.map(channelLabel))].sort();
  return `<h2 class="sr-only" data-visitors-heading tabindex="-1">Visitor reporting</h2><section class="tenant-filter-bar journey-filter-bar visitor-filter-bar" aria-label="Visitor filters"><label><span>Date range</span><select id="visitor-preset"><option value="this-month"${view.preset==="this-month"?" selected":""}>This month</option><option value="last-month"${view.preset==="last-month"?" selected":""}>Last month</option><option value="last-7"${view.preset==="last-7"?" selected":""}>Last 7 days</option><option value="last-30"${view.preset==="last-30"?" selected":""}>Last 30 days</option><option value="custom"${view.preset==="custom"?" selected":""}>Custom</option></select></label><label><span>From</span><input id="visitor-from" type="date" min="${minimum}" max="${data.through}" value="${view.from}" ${view.preset==="custom"?"":"disabled"}></label><label><span>To</span><input id="visitor-to" type="date" min="${minimum}" max="${data.through}" value="${view.to}" ${view.preset==="custom"?"":"disabled"}></label><label><span>Channel</span><select id="visitor-channel"><option value="all">All channels</option>${channels.map(value=>`<option value="${html(value)}"${view.channel===value?" selected":""}>${html(value)}</option>`).join("")}</select></label><label class="tenant-search"><span>Landing page</span><input id="visitor-search" type="search" value="${html(view.search)}" placeholder="Search landing paths"></label><label class="journey-check"><input id="visitor-key-only" type="checkbox" ${view.keyOnly?"checked":""}><span>Had key event</span></label><span class="tenant-cutoff">Data through ${html(data.through)}</span></section><p class="journey-privacy-note">Website visitors can't yet be linked to named renters: the rental happens on CCStorage's domain and no identifier is passed across.</p><section class="tenant-scorecards journey-scorecards" aria-label="Visitor summary">${visitorCards(rows).map(([label,value])=>`<article class="tenant-scorecard journey-scorecard"><span>${html(label)}</span><strong>${number(value)}</strong><small>Selected visitors</small></article>`).join("")}</section><section class="panel journey-channel-panel"><header class="panel-header"><div><h3>First-touch channel mix</h3><p>Source and medium on each visitor's first observed event</p></div></header>${renderChannelMix(rows)}</section><section class="panel tenant-activity-panel journey-table-panel"><header class="panel-header"><div><h3>Visitors</h3><p>Anonymous browser journeys only; visitor IDs are one-way aliases.</p></div></header>${renderVisitorTable(rows,view)}</section>`;
 }
 const EASTERN_TIME=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
 function easternTime(value){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?String(value||""):`${EASTERN_TIME.format(parsed)} ET`;}
 function renderVisitorDialog(visitor,events){return `<section class="journey-dialog-summary"><div><span>Anonymous visitor</span><h3>${html(visitor.vid)}</h3><p>${html(easternTime(visitor.first_seen))} through ${html(easternTime(visitor.last_seen))} · ${number(visitor.sessions)} sessions</p></div><span class="journey-match-badge none">${html(channelLabel(visitor))}</span></section><div class="journey-event-list">${events.map(event=>`<article><time datetime="${html(event.ts)}">${html(easternTime(event.ts))}</time><div><strong>${html(event.name)}</strong><span>${html(event.host)}${html(event.path)} · ${html(event.session)}</span>${event.source?`<small>${html(event.source)} / ${html(event.medium||"(none)")}${event.campaign?` · ${html(event.campaign)}`:""}</small>`:""}</div></article>`).join("")||'<p class="tenant-empty">No events found.</p>'}</div>`;}

 function loadLeadsIndex(){if(!leadsPromise)leadsPromise=fetch("data/restricted/tenants-leads-index.json",{cache:"no-store",credentials:"same-origin"}).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}).then(data=>{if(data?.schema!==LEADS_SCHEMA)throw new Error("Invalid lead index");leadsIndex=data;leadView=initialLeadView(data);return data;}).catch(error=>{leadsUnavailable=true;console.warn("Restricted lead data unavailable:",error.message);return null;});return leadsPromise;}
 function loadVisitorsIndex(){if(!visitorsPromise)visitorsPromise=fetch("data/restricted/tenants-visitors-index.json",{cache:"no-store",credentials:"same-origin"}).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}).then(data=>{if(data?.schema!==VISITORS_SCHEMA)throw new Error("Invalid visitor index");visitorsIndex=data;visitorView=initialVisitorView(data);return data;}).catch(error=>{visitorsUnavailable=true;console.warn("Restricted visitor data unavailable:",error.message);return null;});return visitorsPromise;}
 function loadWeek(file){if(!weekPromises.has(file))weekPromises.set(file,fetch(`data/restricted/${encodeURIComponent(file)}`,{cache:"no-store",credentials:"same-origin"}).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}));return weekPromises.get(file);}
 function getCustomerLeads(customerId){if(!leadsIndex)return leadsUnavailable?null:[];const ids=new Set(leadsIndex.byCustomer?.[customerId]||[]);return leadsIndex.leads.filter(lead=>ids.has(lead.id));}

 function setRestrictedChrome(kind,through){const label=kind==="leads"?"Restricted Meta lead journeys":"Restricted anonymous visitor journeys";document.getElementById("mode-ribbon").textContent=label;document.getElementById("snapshot-label").textContent=`Data through ${through}`;document.getElementById("footer-note").textContent=`${label} · No sharing controls`;}
 function preserveInput(id,renderFunction){const input=document.getElementById(id);if(!input)return;input.oninput=event=>{const position=event.target.selectionStart,value=event.target.value;renderFunction(value);requestAnimationFrame(()=>{const replacement=document.getElementById(id);replacement?.focus({preventScroll:true});replacement?.setSelectionRange(position,position);});};}
 function bindRange(prefix,view,data,renderFunction,minimum,maximum){document.getElementById(`${prefix}-preset`).onchange=event=>{view.preset=event.target.value;const range=presetRange(minimum,maximum,view.preset);if(range)Object.assign(view,range);view.page=1;renderFunction();};for(const side of ["from","to"])document.getElementById(`${prefix}-${side}`).onchange=event=>{view.preset="custom";view[side]=clamp(event.target.value,minimum,maximum);if(view.from>view.to){if(side==="from")view.to=view.from;else view.from=view.to;}view.page=1;renderFunction();};}
 function showLeadDialog(lead,trigger){const title=document.getElementById("tenant-dialog-title"),body=document.getElementById("tenant-dialog-body"),back=document.getElementById("tenant-dialog-back");title.textContent="Lead journey";body.innerHTML=renderLeadDialog(lead);back.hidden=true;back.onclick=null;body.querySelectorAll("[data-journey-customer]").forEach(button=>button.onclick=()=>globalThis.tenantDashboard?.openProfileInDialog(button.dataset.journeyCompany,button.dataset.journeyCustomer,{backLabel:"lead journey",onBack:()=>showLeadDialog(lead)}));if(trigger)globalThis.tenantDashboard?.showDialog(trigger);else title.focus();}
 function showVisitorDialog(visitor,trigger){const title=document.getElementById("tenant-dialog-title"),body=document.getElementById("tenant-dialog-body"),back=document.getElementById("tenant-dialog-back");title.textContent="Visitor timeline";body.innerHTML='<p class="tenant-loading" role="status">Loading visitor timeline…</p>';back.hidden=true;back.onclick=null;globalThis.tenantDashboard?.showDialog(trigger);loadWeek(visitor.week_file).then(data=>{body.innerHTML=renderVisitorDialog(visitor,data?.[visitor.vid]||[]);}).catch(()=>{body.innerHTML='<p class="tenant-empty">This data isn\'t available on this site.</p>';});}

 function renderLeads(){const root=document.getElementById("leads-root");if(!root)return;setRestrictedChrome("leads",leadsIndex?.cutoff||"restricted");if(leadsUnavailable){root.innerHTML='<section class="panel tenant-unavailable" role="status">This data isn\'t available on this site.</section>';return;}if(!leadsIndex){root.innerHTML='<p class="tenant-loading" role="status">Loading restricted lead data…</p>';loadLeadsIndex().then(()=>{if(!document.getElementById("leads-view")?.classList.contains("hidden"))renderLeads();});return;}root.innerHTML=renderLeadsView(leadsIndex,leadView);bindRange("lead",leadView,leadsIndex,renderLeads,leadCoverage(leadsIndex),leadsIndex.cutoff);document.getElementById("lead-campaign").onchange=event=>{leadView.campaign=event.target.value;leadView.page=1;renderLeads();};document.getElementById("lead-match").onchange=event=>{leadView.match=event.target.value;leadView.page=1;renderLeads();};preserveInput("lead-search",value=>{leadView.search=value;leadView.page=1;renderLeads();});root.querySelectorAll("[data-journey-sort]").forEach(button=>button.onclick=()=>{leadView.direction=leadView.sort===button.dataset.journeySort?-leadView.direction:-1;leadView.sort=button.dataset.journeySort;leadView.page=1;renderLeads();});root.querySelectorAll("[data-lead-page]").forEach(button=>button.onclick=()=>{leadView.page=Number(button.dataset.leadPage);renderLeads();});root.querySelectorAll("[data-lead-id]").forEach(button=>button.onclick=()=>showLeadDialog(leadsIndex.leads.find(row=>row.id===button.dataset.leadId),button));}
 function renderVisitors(){const root=document.getElementById("visitors-root");if(!root)return;setRestrictedChrome("visitors",visitorsIndex?.through||"restricted");if(visitorsUnavailable){root.innerHTML='<section class="panel tenant-unavailable" role="status">This data isn\'t available on this site.</section>';return;}if(!visitorsIndex){root.innerHTML='<p class="tenant-loading" role="status">Loading restricted visitor data…</p>';loadVisitorsIndex().then(()=>{if(!document.getElementById("visitors-view")?.classList.contains("hidden"))renderVisitors();});return;}root.innerHTML=renderVisitorsView(visitorsIndex,visitorView);bindRange("visitor",visitorView,visitorsIndex,renderVisitors,visitorCoverage(visitorsIndex),visitorsIndex.through);document.getElementById("visitor-channel").onchange=event=>{visitorView.channel=event.target.value;visitorView.page=1;renderVisitors();};document.getElementById("visitor-key-only").onchange=event=>{visitorView.keyOnly=event.target.checked;visitorView.page=1;renderVisitors();};preserveInput("visitor-search",value=>{visitorView.search=value;visitorView.page=1;renderVisitors();});root.querySelectorAll("[data-journey-sort]").forEach(button=>button.onclick=()=>{visitorView.direction=visitorView.sort===button.dataset.journeySort?-visitorView.direction:-1;visitorView.sort=button.dataset.journeySort;visitorView.page=1;renderVisitors();});root.querySelectorAll("[data-visitor-page]").forEach(button=>button.onclick=()=>{visitorView.page=Number(button.dataset.visitorPage);renderVisitors();});root.querySelectorAll("[data-visitor-id]").forEach(button=>button.onclick=()=>showVisitorDialog(visitorsIndex.visitors.find(row=>row.vid===button.dataset.visitorId),button));}
 function render(view){if(typeof document==="undefined")return;if(view==="leads")renderLeads();else if(view==="visitors")renderVisitors();}

 return {initialLeadView,initialVisitorView,leadRows,visitorRows,renderLeadsView,renderLeadDialog,renderVisitorsView,renderVisitorDialog,loadLeadsIndex,getCustomerLeads,render};
});
